### ISSUE TITLE
bower_components in repo?

### ISSUE THREAD

**Issue by adamretter** [eXist-db/existdb-dashboard#6]
For sure I am no JavaScript developer. But it looks to me like you accidentally committed your bower repo to the GitHub repository? If I understand Bower correctly, its meant to download the things you need on demand from the bower file... right?

I can help rebase the repo so it looks like those files were never committed if you like? It would also reduce the repo size and checkout time.

**Comment by joewiz** [comment]
My understanding is that it's included so that users without bower, npm, etc.—users who have ONLY ant—are able to build and deploy the app.

**Comment by adamretter** [comment]
@joewiz Okay I see.

That being said, I think it is a terrible idea though. Building a project requires certain tools, like Java and Ant for example, no reason building this shouldn't also require bower and npm. If that is tricky a script could be provided that brew/apt-get/yum installs the lot of them...

The problem with having these in the repo, is they very quickly become outdated and it kinda defeats the whole point of using bower in the first place.

**Comment by duncdrum** [comment]
I agree with @adamretter 
> As nodejs (npm) is not available or common to everyone the dependencies are therefore kept in the repo which eases building the app.

does not convince me, with 6,433,401,333 downloads last week(!) my guess is there are more nodejs / npm users than ant and exist-db users combined. As such the question is what happens when users who do have nodejs npm and bower installed try to  build the source code. Will that build be identical to the one in here?

what about unsupervised builds, we are greatly inflating the data-traffic if these clone the repo. Virtually every Ci server has npm * co installed and then will run it, so the `_modules` get overwritten and we lost reproducible builds. 

That article quoted in the readme is from 2013(!), lots of things have changed in node, npm and bower. If we want treeshaking we can have it today.

**Comment by JoernT** [comment]
this is a won't fix for me and i really don't want to get into this discussion.

As the only maintainer of this app i certainly won't change the situation as it will be pointless when moving on to Polymer 3 which does not use bower any more. Though the migration is still a bit ahead it doesn't make sense to rework the stuff now just to throw it away in a few month.

**Comment by wolfgangmm** [comment]
If I read the messages correctly, Chrome will stop support for HTML imports after March, so by then we likely have to say goodbye to bower and polymer 2 anyway.

**Comment by adamretter** [comment]
March is pretty soon. Presumably we should do that work before we switch over to this?

**Comment by joewiz** [comment]
Migrating further discussion to https://github.com/eXist-db/existdb-dashboard/issues/16.
