### ISSUE TITLE
Scheduler plugin

### ISSUE THREAD

**Issue by joewiz** [eXist-db/existdb-dashboard#7]
From the Sep 10 community call notes, Joern said:

> There was never a scheduler app in dashboard right? My first take always was to first reproduce what the old dashboard offered. May however be a good idea but IMO nothing that would block a release of the dashboard." 

I just checked the dashboard repo, and found that there was a scheduler plugin, which was (a) created by @lcahlander back in 2013 https://github.com/eXist-db/dashboard/commit/fe962a803eff7fa8f7f822a5ede26242e44ed840 and (b) disabled by @wolfgangmm in February of this year with https://github.com/eXist-db/dashboard/commit/214d58a95068b892988f10a737c80932048edec1. The code for the plugin is still in the source at https://github.com/eXist-db/dashboard/tree/master/plugins/scheduler, and it's still mentioned in the docs at http://exist-db.org/exist/apps/doc/troubleshooting.xml#emergency. 

I see 3 choices that would allow us to close this and thus account for this feature before officially moving away from the old dashboard:

1. Reimplement scheduler in the new dashboard
2. Move scheduler to monex
3. Drop the feature - but announce this in release notes

(Note that collection browser was dropped as a duplicate of a feature in eXide, and the shutdown button was dropped as "unused" except by Dannes - but the documentation still refers to both of these panes - so I'll let this serve as a reminder that documentation updates are also needed.)

**Comment by JoernT** [comment]
Fact is that the scheduler plugin wasn't available for years now. Further there certainly was a reason for disabling it back then. It's a long time so i don't know if @wolfgangmm is remembering. 

I'm currently loaded with half a dozen projects so it's not likely that i find time for re-implementing it in within the next weeks. So that would effectively block a 5.0 for a while then. 

IMO it's not worth arguing about a (obviously) deprecated plugin. Of course there are many feature you may want to see in the new dashboard. If i would work down my wishlist we couldn't release within next months.

**Comment by wolfgangmm** [comment]
The previous functionality of the scheduler plugin is included in monex and was thus redundant in the dashboard:

1. showing active tasks
2. allowing users to kill a query

I think we can just drop it.

**Comment by duncdrum** [comment]
+1 for dead code removal
+10 for updating docs 
See eXist-db/documentation#101

**Comment by JoernT** [comment]
@all i guess that means that we can drop a scheduler plugin for the new dashboard.
